### ISSUE TITLE
Invalid login but with a valid account

### ISSUE THREAD

**Issue by marciovicente** [mcorp/locasms#2]
I'm trying send sms from a RoR application with `locasms` client. Look this code below:

```
 client_SMS = LocaSMS::Client.new 'XXXXXXX', Rails.application.secrets.sms_password
 client_SMS.balance 
   => NameError: uninitialized constant LocaSMS::RestClient::InvalidLogin
```

I can login in browser (with same login and password), but with ruby client, this code always returns the same exception. 

Do you still supporting this gem? @vyper @adilsoncarvalho

Best regards!

**Comment by vyper** [comment]
You are using that login?

Login for api is different of login for dashboard.

**Comment by marciovicente** [comment]
@vyper, where can I get the login for API? I'm using login to dashboard. I can't access a dashboard specific to API.

**Comment by vyper** [comment]
@marciovicente try create other user checking `api` access...

![image](https://cloud.githubusercontent.com/assets/22549/6554930/8249b0d8-c63f-11e4-8384-d581992c5daf.png)

**Comment by marciovicente** [comment]
I can't find this form. Where's the `api access`. I just found the general dashboard, without users manager. @vyper

**Comment by vyper** [comment]
I access this option on:

- Left menu
- Click on `Gerenciamento de usuários`
- Click on button `Novo usuário`

For more information, contact LocaSMS support...
