### ISSUE TITLE
New IP address after March 29, 2016

### ISSUE THREAD

**Issue by douglasresende** [mcorp/locasms#7]
Just change the IP address used to connect to the service from ```209.133.196.250``` to ```54.173.24.177``` starting at March 29,  #2016.

Endpoint message received:
![captura de tela 2016-03-29 as 10 17 05](https://cloud.githubusercontent.com/assets/1786872/14110922/04198586-f59f-11e5-990f-995b31a9ab4c.png)

#6

**Comment by adilsoncarvalho** [comment]
It got solved on the PR #6
